from setuptools import setup, find_packages

setup(name='Ninja-IDE',
      version='2.3+dev',
      description='Cross-platform IDE focused on Python application development',
      author='The Ninja IDE Developers',
      url='http://ninja-ide.org',
      download_url='https://github.com/ninja-ide/ninja-ide',
      license='GPLv3+',
      packages=find_packages(),
      python_requires='>=3.4',
      install_requires=['pyqt5'],
      extra_require={'tests': ['pytest', 'pytest-qt']},
      include_package_data=True,
      zip_safe=False,
      classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3 :: Only',
        'Topic :: Software Development',
        'Topic :: Text Editors',
        'Topic :: Text Editors :: Integrated Development Environments (IDE)',
        ],
      project_urls={
        'Bug Reports': 'https://github.com/ninja-ide/ninja-ide/issues',
        'Sourcecode': 'https://github.com/ninja-ide/ninja-ide',
        'Donations': 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8TESZPNRD59H6',
        'Flattr': 'https://button.flattr.com/flattr/T1gcadsvoNbmRMQHL4xPIVKnuJLkWephrcCdTfmySQ8%7Cuxo2PSTXxruOKExXGGt_IjdY-WOfiu4OG1P5zehE2_Y%7CQHSnMfEto2NAuneuPPhKdDW_D9Rjx0qfLlJfFiBcvkBvrLcR2Hra5cAY22-I6azaUP-sbIWpPMAjLmJbk6LQXrQQQ6DhmxTg2-7Dsyjyhgfatj6OuBEB09F9-0htyFOd',
      },)
